/// Protocol-level errors shared by host code and the onchain program.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ProtocolError {
    InvalidInstructionData = 1,
    EmptyInstructionData = 2,
    UnknownInstruction = 3,
    InstructionNotImplemented = 4,
    InvalidInstructionLength = 5,
    InvalidAccountData = 6,
    InvalidAccountDiscriminator = 7,
    UnsupportedAccountVersion = 8,
    InvalidAccountLength = 9,
    InvalidJobState = 10,
    InvalidStateTransition = 11,
    InvalidReceiptLength = 12,
    InvalidReceiptDomain = 13,
    UnsupportedReceiptVersion = 14,
    InvalidReceiptTimestamps = 15,
    InvalidBoolean = 16,
    InvalidProviderStatus = 17,
    IntegerOverflow = 18,
    Unauthorized = 19,
    ProtocolPaused = 20,
    AlreadyInitialized = 21,
    UninitializedAccount = 22,
    InvalidPda = 23,
    InvalidBump = 24,
    InvalidOwner = 25,
    InvalidMint = 26,
    InvalidTokenProgram = 27,
    InvalidTokenAccount = 28,
    InvalidTokenAccountOwner = 29,
    InvalidTokenAccountMint = 30,
    InvalidTokenAccountAuthority = 31,
    InvalidAssociatedTokenAccount = 32,
    TokenAccountFrozen = 33,
    InsufficientFunds = 34,
    InsufficientBond = 35,
    BondLocked = 36,
    DeadlineExpired = 37,
    DeadlineNotReached = 38,
    InvalidDeadlineOrder = 39,
    InvalidAmount = 40,
    InvalidPubkey = 41,
    DuplicateExecutionKey = 42,
    ExecutionKeyNotFound = 43,
    ExecutionKeyLimit = 44,
    InvalidReceiptField = 45,
    InvalidEd25519Instruction = 46,
    MissingEd25519Instruction = 47,
    InvalidSignature = 48,
    EscrowNotEmpty = 49,
    EscrowUnexpectedBalance = 50,
    ChallengeBondMustBeZero = 51,
    InvalidChallengeStatus = 52,
    MathOverflow = 53,
    AccountNotWritable = 54,
    MissingSignature = 55,
    InvalidRentRecipient = 56,
    InvalidConfig = 57,
    ProviderInactive = 58,
    FutureTimestamp = 59,
    ReceiptExpired = 60,
}

impl ProtocolError {
    pub const fn code(self) -> u32 {
        self as u32
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InvalidInstructionData => "invalid instruction data",
            Self::EmptyInstructionData => "empty instruction data",
            Self::UnknownInstruction => "unknown instruction",
            Self::InstructionNotImplemented => "instruction not implemented",
            Self::InvalidInstructionLength => "invalid instruction length",
            Self::InvalidAccountData => "invalid account data",
            Self::InvalidAccountDiscriminator => "invalid account discriminator",
            Self::UnsupportedAccountVersion => "unsupported account layout version",
            Self::InvalidAccountLength => "invalid account length",
            Self::InvalidJobState => "invalid job state",
            Self::InvalidStateTransition => "invalid state transition",
            Self::InvalidReceiptLength => "invalid receipt length",
            Self::InvalidReceiptDomain => "invalid receipt domain",
            Self::UnsupportedReceiptVersion => "unsupported receipt version",
            Self::InvalidReceiptTimestamps => "invalid receipt timestamps",
            Self::InvalidBoolean => "invalid boolean byte",
            Self::InvalidProviderStatus => "invalid provider status",
            Self::IntegerOverflow => "integer overflow",
            Self::Unauthorized => "unauthorized",
            Self::ProtocolPaused => "protocol paused",
            Self::AlreadyInitialized => "already initialized",
            Self::UninitializedAccount => "uninitialized account",
            Self::InvalidPda => "invalid pda",
            Self::InvalidBump => "invalid bump",
            Self::InvalidOwner => "invalid owner",
            Self::InvalidMint => "invalid mint",
            Self::InvalidTokenProgram => "invalid token program",
            Self::InvalidTokenAccount => "invalid token account",
            Self::InvalidTokenAccountOwner => "invalid token account owner",
            Self::InvalidTokenAccountMint => "invalid token account mint",
            Self::InvalidTokenAccountAuthority => "invalid token account authority",
            Self::InvalidAssociatedTokenAccount => "invalid associated token account",
            Self::TokenAccountFrozen => "token account frozen",
            Self::InsufficientFunds => "insufficient funds",
            Self::InsufficientBond => "insufficient bond",
            Self::BondLocked => "bond locked",
            Self::DeadlineExpired => "deadline expired",
            Self::DeadlineNotReached => "deadline not reached",
            Self::InvalidDeadlineOrder => "invalid deadline order",
            Self::InvalidAmount => "invalid amount",
            Self::InvalidPubkey => "invalid pubkey",
            Self::DuplicateExecutionKey => "duplicate execution key",
            Self::ExecutionKeyNotFound => "execution key not found",
            Self::ExecutionKeyLimit => "execution key limit",
            Self::InvalidReceiptField => "invalid receipt field",
            Self::InvalidEd25519Instruction => "invalid ed25519 instruction",
            Self::MissingEd25519Instruction => "missing ed25519 instruction",
            Self::InvalidSignature => "invalid signature",
            Self::EscrowNotEmpty => "escrow not empty",
            Self::EscrowUnexpectedBalance => "escrow unexpected balance",
            Self::ChallengeBondMustBeZero => "challenge bond must be zero",
            Self::InvalidChallengeStatus => "invalid challenge status",
            Self::MathOverflow => "math overflow",
            Self::AccountNotWritable => "account not writable",
            Self::MissingSignature => "missing signature",
            Self::InvalidRentRecipient => "invalid rent recipient",
            Self::InvalidConfig => "invalid config",
            Self::ProviderInactive => "provider inactive",
            Self::FutureTimestamp => "future timestamp",
            Self::ReceiptExpired => "receipt expired",
        }
    }
}

impl core::fmt::Display for ProtocolError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(feature = "std")]
impl std::error::Error for ProtocolError {}
